#!/usr/bin/env bash
set -euo pipefail

PLAN_FILE="${1:?Usage: $0 <plan-output-file> <environment>}"
ENVIRONMENT="${2:-prod}"

: "${GITHUB_TOKEN:?GITHUB_TOKEN is required}"
: "${PR_NUMBER:?PR_NUMBER is required}"

if [ ! -f "$PLAN_FILE" ]; then
  echo "Error: plan output file '$PLAN_FILE' not found" >&2
  exit 1
fi

PLAN_OUTPUT=$(sed -n '/^Terraform used the selected providers/,/^Releasing state lock/p' "$PLAN_FILE")
if [ -z "$PLAN_OUTPUT" ]; then
  PLAN_OUTPUT=$(cat "$PLAN_FILE")
fi

MAX_LEN=60000
TRUNCATED_NOTICE=""
if [ "${#PLAN_OUTPUT}" -gt "$MAX_LEN" ]; then
  PLAN_OUTPUT="${PLAN_OUTPUT:0:$MAX_LEN}"
  TRUNCATED_NOTICE=$'\n\n> ⚠️ Output truncated at 60 000 characters. Run `terraform plan` locally to see the full output.'
fi

RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-}/actions/runs/${GITHUB_RUN_ID:-}"

COMMENT_BODY=$(printf '## Terraform Plan — `%s`\n\n<details><summary>Show Plan</summary>\n\n```terraform\n%s\n```%s\n\n</details>\n\n*Plan generated by GitHub Actions · [View run](%s)*\n' \
  "$ENVIRONMENT" \
  "$PLAN_OUTPUT" \
  "$TRUNCATED_NOTICE" \
  "$RUN_URL")

EXISTING_ID=$(curl -s \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
  | jq -r '.[] | select(.user.type == "Bot") | select(.body | startswith("## Terraform Plan")) | .id' \
  | head -1)

PAYLOAD=$(jq -n --arg body "$COMMENT_BODY" '{body: $body}')

if [ -n "$EXISTING_ID" ]; then
  curl -s -X PATCH \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -H "Content-Type: application/json" \
    "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/comments/$EXISTING_ID" \
    -d "$PAYLOAD" > /dev/null
  echo "Updated existing plan comment (id=$EXISTING_ID)"
else
  curl -s -X POST \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -H "Content-Type: application/json" \
    "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
    -d "$PAYLOAD" > /dev/null
  echo "Created new plan comment"
fi
